---
title: "Results of Ordered Likelihood Analysis"
author: "Devan Becker"
date: "`r Sys.Date()`"
output:
    pdf_document:
      citation_package: natbib
      keep_tex: yes
---

```{r data_prep}
library(here)
library(dplyr)
library(tidyr)
library(stringr)
library(ggplot2)
csvs <- lapply(
    list.files(here("data/pangordlineages"),
        full.names = TRUE),
    read.csv
    ) %>%
    bind_rows() %>%
    separate(col = taxon, 
        into = c("dummy", "acc", "lik", "subs"),
        sep = "_") %>%
    mutate(nsubs = str_count(subs, "2"),
        lik = as.numeric(lik)) %>%
    group_by(acc) %>%
    mutate(order = 1:n()) %>%
    ungroup()

```

```{r change_in_weight}
ggplot(csvs) +
    aes(x = order, y = lik, colour = factor(acc)) + 
    geom_point() + geom_line() +
    theme(legend.position = "none")
```


```{r sampling_results}
samp_csvs <- list.files(here("data/", "pangolineages"),
    pattern = "*_d.csv",
    full.names = TRUE)

# Remove any copies
samp_csvs <- samp_csvs[!grepl("-1", samp_csvs)]

# Bring them into one data frame
lins <- bind_rows(lapply(samp_csvs, read.csv))

# Taxon is encoded as _ACCSESSIONNUMBER.ID, split into ACCESSIONNUMBER and ID
lins <- lins %>%
    separate(col = "taxon", sep = "\\.",
        into = c("taxon", "sample")) %>%
    mutate(taxon = str_replace(taxon, "\\_", ""))

badlins <- table(lins$taxon)
badlins <- names(badlins[which(badlins < 5000)])
cat(length(badlins), " runs were removed for having too few samples.")
lins <- filter(lins, !taxon %in% badlins)

#### Visualize the uncertainty in the base calls ----
taxons <- sort(unique(lins$taxon))
length(taxons)
```


TODO: 

- Good summaries for ord.
- Plot them.

```{r}
lin_sum <- lins %>%
    group_by(taxon) %>%
    summarise(
        maxperc = mean(lineage == names(sort(table(lineage),
            decreasing = TRUE)[1])),
        uniques = length(unique(lineage)),
        minpango = min(probability),
        maxpango = max(probability),
        menpango = mean(probability),
        max = names(sort(table(lineage), decreasing = TRUE))[1])

ord_sum <- csvs %>% 
    group_by(acc) %>%
    summarise(
        maxperc = mean(lineage == names(sort(table(lineage),
            decreasing = TRUE)[1])),
        uniques = length(unique(lineage)),
        minpango = min(probability),
        maxpango = max(probability),
        menpango = mean(probability),
        max = names(sort(table(lineage), decreasing = TRUE))[1])
```





