# Check for installed packages, install when necessary
suppressPackageStartupMessages({
    if(!require("sung", quietly = TRUE)) system("sh ../../sung/Rpkg/install-sung.sh")
    if(!require("snow", quietly = TRUE)) install.packages("snow")
    if(!require("snowfall", quietly = TRUE)) install.packages("snowfall")
    if(!require("gridExtra", quietly = TRUE)) install.packages("gridExtra")
    if(!require("dplyr", quietly = TRUE)) install.packages("dplyr")
    if(!require("rncl", quietly = TRUE)) install.packages("rncl")
    if(!require("phylobase", quietly = TRUE)) install.packages("phylobase")
    if(!require("BiocManager", quietly = TRUE)) install.packages("BiocManager")
    if(!require("devtools", quietly = TRUE)) install.packages("devtools")
    if(!require("compoisson", quietly = TRUE)) devtools::install_url("https://cran.r-project.org/src/contrib/Archive/compoisson/compoisson_0.3.tar.gz")
    if(!require("phylosim", quietly = TRUE)) devtools::install_url("https://cran.r-project.org/src/contrib/Archive/phylosim/phylosim_3.0.5.tar.gz")
    if(!require("phytools", quietly = TRUE)) install.packages("phytools")
})